### ISSUE TITLE
Wrong/ Deprecated Addresses in the 'sdk/eth-sdk/config.ts' file, and Private Repo Dependencies for `_[protocol]Info.ts` generation script

### ISSUE THREAD

**Issue by coviccinelle** [karpatkey/defi-kit#284]
### Summary
Hello team!
While integrating Aave V3 on the Arbitrum network, I encountered three primary issues in Defi-Kit related to address management and dependencies for generating `_[protocol]Info.ts`.
I have detailed each below, including potential solutions. I'm also proposing a new TypeScript script as an alternative to the current Python script, which has dependencies on private repos.

---

### Identified Issues

1. **Outdated/Wrong Addresses**:
   - Certain addresses in Defi-Kit for Aave V3 on multiple networks are outdated or incorrect when compared with the official Aave documentation (https://aave.com/docs/resources/addresses).
   - - **Incorrect Address Assignment**:
   - The address for `stableDebtWXDAI` on Aave V3 for Gnosis in the `sdk/eth-sdk/config.ts` file is currently set to `0x281963D7471eCdC3A2Bd4503e24e89691cfe420D`, which is the address for `variableDebtWXDAI`. This should be corrected to ensure accurate address mapping.

2. **Deprecated Addresses**:
   - All instances of `stableDebtWETH` are deprecated across relevant networks and should now be set to the placeholder address `0x0000000000000000000000000000000000000000` to reflect this status.

3. **Private Repo Dependencies in Python Script**:
   - The current Python script for generating `_[protocol]Info.ts` requires dependencies from private repositories, which may restrict its usage and portability.

---

### Suggested Solutions

1. **Correct and Update Addresses**:
   - **Replace deprecated addresses** (e.g., `stableDebtWETH`) with `0x0000000000000000000000000000000000000000`.
   - **Update incorrect addresses** for each relevant network (Mainnet, Gnosis, Arbitrum One) as detailed in the official Aave V3 documentation.

2. **Alternative TypeScript Script**:
   - I have developed an alternative TypeScript script that could replace the current Python script for generating _[protocol]Info.ts to meet my needs at this stage.
   - **Dependencies**:
     - Requires `ProtocolDataProvider`, ABIs, and protocol name.
   - This TypeScript version eliminates the dependency on private repositories, making it easier to use and maintain across various setups.

---

### Action Items

1. **Review and implement address updates** in Defi-Kit.
2. **Deprecate references** to assets like `stableDebtWETH`.
3. **Consider adopting the new TypeScript script** for `_[protocol]Info.ts` generation to avoid private repo dependencies.
https://github.com/hopperlabsxyz/protocol-scripting

---

### Next Steps
If these updates align with project goals, I’d be happy to open a PR with the corrected addresses and the new TypeScript script for review. Let me know if any additional details would be helpful!

---

Thank you!

**Comment by jfschwarz** [comment]
Hey @coviccinelle, check out https://github.com/karpatkey/defi-kit/pull/286 which seems to address some of the issues you describe. would be awesome to get your review on that PR!

https://github.com/hopperlabsxyz/protocol-scripting seem to be a private repository

**Comment by sideris** [comment]
Thank you @coviccinelle

We will take a look at the above.

**Comment by nledo** [comment]
This issue was resolved in [PR #288](https://github.com/karpatkey/defi-kit/pull/288). 
Adopting the new TypeScript scripts will be considered in the near future.
